[install]
# Prefer workspace dependencies
prefer-workspace-packages = true

[test]
# Default test runner configuration
runner = "bun"
preload = ["./happy-dom.ts"]

[lint]
# ESLint configuration
enabled = true

[performance]
# Performance optimizations
auto-install = true
cache = true
