site_name: Antar Platform Documentation
site_description: Smart delivery platform for Southeast Asian merchants
site_author: Antar Team
copyright: Copyright &copy; 2024 Antar
repo_url: https://github.com/Dolpheyn/antar
repo_name: Dolpheyn/antar
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Plus Jakarta Sans
    code: JetBrains Mono
  favicon: assets/favicon.png
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
    - Home: index.md
    - Notebook:
        - Overview: notebook/index.md
        - AI Workspace:
            - 2024-12-21:
                - Pyright Analysis: notebook/ai-workspace/2024-12-21/pyright_analysis.md
                - Visual Testing Refactoring: notebook/ai-workspace/2024-12-21/visual_testing_refactoring.md
                - Visual Testing Strategy: notebook/ai-workspace/2024-12-21/visual_testing_strategy.md
                - Floatrect Type Safety: notebook/ai-workspace/2024-12-21/floatrect_type_safety.md
                - Console Investigation: notebook/ai-workspace/2024-12-21/console_investigation.md
                - Type Safety Plan: notebook/ai-workspace/2024-12-21/type_safety_plan.md
                - Visual Testing Diagnostic: notebook/ai-workspace/2024-12-21/visual_testing_diagnostic.md
            - 2024-12-22:
                - Refined Visual Testing Network Challenges: notebook/ai-workspace/2024-12-22/refined-visual-testing-network-challenges.md
                - Pyright Visual Script Fixes: notebook/ai-workspace/2024-12-22/2024-12-22-pyright-visual-script-fixes.md
                - Visual Testing Network Challenges: notebook/ai-workspace/2024-12-22/2024-12-22-visual-testing-network-challenges.md
                - Flake8 Visual Script Fixes: notebook/ai-workspace/2024-12-22/2024-12-22-flake8-visual-script-fixes.md
            - 2024-12-23:
                - Bulk Upload and Route Optimization:
                    - Project Overview: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/00-project-overview.md
                    - Bulk Upload Route Optimization Spec: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/01-bulk-upload-route-optimization-spec.md
                    - Route Optimization Complexity Levels: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/02-route-optimization-complexity-levels.md
                    - Intelligent Clustering Reflection: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/03-intelligent-clustering-reflection.md
                    - Technological Progression: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/04-technological-progression.md
                    - Antar Route Optimization Reality Check: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/05-antar-route-optimization-reality-check.md
                    - User Stories and Personas: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/06-user-stories-and-personas.md
                    - Technical Design Workshop Agenda: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/07-technical-design-workshop-agenda.md
                    - Workshop Minutes and Action Items: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/08-workshop-minutes-and-action-items.md
                    - Route Optimization Strategy: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/09-route-optimization-strategy.md
                    - Engineering Specification: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/10-engineering-specification.md
                    - API Design: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/11-api-design.md
                    - Technical Implementation Go: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/12-technical-implementation-go.md
                    - Principal Engineer Implementation Strategy: notebook/ai-workspace/2024-12-23/bulk upload and route optimization/13-principal-engineer-implementation-strategy.md
                    - Dependency Vulnerability Scan CI Error: notebook/ai-workspace/2024-12-23/dependency vulnerability scan ci error.md
                    - Docs CI Error: notebook/ai-workspace/2024-12-23/docs ci error.md
                    - Frontend CI Error: notebook/ai-workspace/2024-12-23/frontend ci error.md
            - 2024-12-25:
                - Why We Exists: notebook/ai-workspace/2024-12-25/why-we-exists.md
            - 2024-12-26:
                - OSRM Self-Hosting: notebook/ai-workspace/2024-12-26-osrm-self-hosting.md
        - Features:
            - Bulk Upload:
                - Overview: notebook/features/bulk-upload/README.md
                - Business Context: notebook/features/bulk-upload/overview/business-context.md
                - Technical:
                    - Architecture: notebook/features/bulk-upload/technical/architecture.md
                    - Performance: notebook/features/bulk-upload/technical/performance.md
                    - Components:
                        - File Upload: notebook/features/bulk-upload/technical/components/file-upload.md
                        - Route Grouping: notebook/features/bulk-upload/technical/components/route-grouping.md
                        - Map Visualization: notebook/features/bulk-upload/technical/components/map-visualization.md
                - User Experience:
                    - Index: notebook/features/bulk-upload/ux/index.md
                    - Interface Guidelines: notebook/features/bulk-upload/ux/interface-guidelines.md
                    - Error Handling: notebook/features/bulk-upload/ux/error-handling.md
                    - Interactions: notebook/features/bulk-upload/ux/interactions.md
                    - Flow: notebook/features/bulk-upload/ux/flow.md
                    - Components: notebook/features/bulk-upload/ux/components.md
                - Implementation:
                    - Index: notebook/features/bulk-upload/implementation/index.md
                    - Engineering Specifications: notebook/features/bulk-upload/implementation/engineering-specifications.md
                - UI:
                    - Index: notebook/features/bulk-upload/ui/index.md
                    - Responsive: notebook/features/bulk-upload/ui/responsive.md
                    - Animations: notebook/features/bulk-upload/ui/animations.md
                    - Components: notebook/features/bulk-upload/ui/components.md
                - Archive:
                    - Index: notebook/features/bulk-upload/archive/index.md
                    - Context: notebook/features/bulk-upload/archive/context.md
                    - Technical: notebook/features/bulk-upload/archive/technical.md
    - Process:
        - Decisions: notebook/process/decisions.md
        - Self Agency: notebook/process/self-agency.md
    - Tech:
        - Frontend:
            - Overview: notebook/tech/frontend/README.md
            - Development:
                - Workflow: notebook/tech/frontend/development/workflow.md
                - Technology Stack: notebook/tech/frontend/development/technology-stack.md
            - Maintenance:
                - Tasks: notebook/tech/frontend/maintenance/tasks.md
            - Setup:
                - Configuration: notebook/tech/frontend/setup/configuration.md
                - Installation: notebook/tech/frontend/setup/installation.md
                - Dependencies: notebook/tech/frontend/setup/dependencies.md
            - Testing:
                - Strategy: notebook/tech/frontend/testing/strategy.md
                - Tools: notebook/tech/frontend/testing/tools.md
                - Examples: notebook/tech/frontend/testing/examples.md
            - Archive:
                - Testing Strategy: notebook/tech/frontend/_archive/testing-strategy.md
                - Frontend Development Journey: notebook/tech/frontend/_archive/frontend-development-journey.md
            - Implementation:
                - Client Processing: notebook/tech/implementation/client.md
                - Route Optimization: notebook/tech/implementation/routes.md
                - User Interface: notebook/tech/implementation/ui.md
    - Product:
        - Overview: product/README.md
        - Features: product/features.md
        - Success Stories: product/stories.md
    - Roadmap:
        - Overview: roadmap/index.md
        - Phase 1 Foundation: roadmap/phase-1-foundation.md
        - Initiatives:
            - Documentation System: roadmap/initiatives/documentation-system.md
            - Visual Testing: roadmap/initiatives/visual-testing.md
        - Templates:
            - Milestone Plan: roadmap/templates/milestone-plan.md
    - Tech Overview:
        - Overview: tech/index.md
        - Architecture: tech/architecture.md
        - CI/CD: tech/ci-cd.md
        - Frontend Notes: tech/frontend-notes.md
        - Integration Guidelines: tech/integration-guidelines.md
        - Performance Requirements: tech/performance-requirements.md
        - Roadmap:
            - Overview: tech/roadmap/index.md
            - Phase 1:
                - Overview: tech/roadmap/phase-1/index.md
                - Architecture: tech/roadmap/phase-1/architecture.md
                - Integration: tech/roadmap/phase-1/integration.md
        - Specs:
            - API:
                - Overview: tech/specs/api/index.md
            - Data:
                - Overview: tech/specs/data/index.md
            - Security:
                - Overview: tech/specs/security/index.md
        - Story:
            - Concepts: tech/story/concepts.md
            - Vision: tech/story/vision.md
        - System Architecture: tech/system-architecture.md
        - Templates:
            - API Spec: tech/templates/api-spec.md

plugins:
  - search
  - include-markdown
  - mermaid2:
      version: 10.6.1

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
