site_name: Delivery Aggregator Platform
site_description: Intelligent delivery service aggregation platform for Malaysian merchants
site_author: Your Team
repo_url: https://github.com/Dolpheyn/the-project
repo_name: Dolpheyn/the-project
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    # Navigation
    - navigation.instant  # Instant loading
    - navigation.tracking  # URL tracking
    - navigation.sections  # Sections fold
    - navigation.indexes  # Section index pages
    - navigation.expand   # Expand all sections
    - navigation.top     # Back to top button
    - toc.follow         # Follow TOC while scrolling
    - toc.integrate      # Integrate TOC into navigation
    # Search
    - search.suggest     # Search suggestions
    - search.highlight   # Search highlighting
    - search.share       # Search sharing
    # UI/UX
    - header.autohide    # Hide header on scroll
    - announce.dismiss   # Dismissable announcements
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Fira Sans, Droid Sans, Helvetica Neue, sans-serif
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search
  - include-markdown
  - mermaid2:
      version: 10.6.1
      arguments:
        securityLevel: 'loose'
        theme: default
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3
      slugify: !!python/name:pymdownx.slugs.uslugify

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Dolpheyn
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

nav:
  - Home: index.md
  - Story Idea:
    - story-idea/index.md
    - Delivery Aggregator:
      - story-idea/delivery-aggregator/index.md
      - Feature Concept: story-idea/delivery-aggregator/feature-concept.md
  - User Personas: user-personas/index.md
  - Project Roadmap:
    - project-roadmap/index.md
    - Initiatives:
      - Documentation System: project-roadmap/initiatives/documentation-system.md
  - Technical Specifications:
    - technical-specifications/index.md
    - System Architecture: technical-specifications/system-architecture.md
    - Data Models: technical-specifications/data-models.md
    - API Specifications: technical-specifications/api-specifications.md
    - Security Requirements: technical-specifications/security-requirements.md
    - Performance Requirements: technical-specifications/performance-requirements.md
    - Integration Guidelines: technical-specifications/integration-guidelines.md
    - CI/CD Pipeline: technical-specifications/ci-cd.md
  - AI Knowledge:
    - Project Areas: ai-knowledge/project-areas-context.md
    - User Context: ai-knowledge/user-context.md
    - Initiative Context: ai-knowledge/initiative-context.md
