site_name: Antar
site_description: Smart delivery platform for Southeast Asian merchants
site_author: Antar Team
copyright: Copyright &copy; 2024 Antar
repo_url: https://github.com/Dolpheyn/antar
repo_name: Dolpheyn/antar
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Plus Jakarta Sans
    code: JetBrains Mono
  favicon: assets/favicon.png
  logo: assets/logo.png
  features:
    # Navigation
    - navigation.instant  # Instant loading
    - navigation.instant.prefetch # Prefetch when user hovers
    - navigation.instant.progress
    - navigation.tracking  # URL tracking
    - navigation.sections  # Sections fold
    - navigation.indexes  # Section index pages
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top     # Back to top button
    - toc.follow         # Follow TOC while scrolling
    # Search
    - search.suggest     # Search suggestions
    - search.highlight   # Search highlighting
    - search.share       # Search sharing
    # UI/UX
    - announce.dismiss   # Dismissable announcements
    - content.tabs.link  # Content tabs link
    - content.code.annotation  # Content code annotation
    - content.code.copy  # Content code copy

nav:
  - Home: index.md
  - Product:
    - Overview: product/overview.md
    - Features: product/feature-concept.md
    - Use Cases: product/user-stories.md
    - Roadmap: 
      - Overview: product/roadmap/index.md
  - Tech:
    - Overview: tech/index.md
    - Architecture:
      - System Design: tech/system-architecture.md
      - Data Models: tech/data-models.md
    - Integration:
      - API Reference: tech/api-specifications.md
      - Guidelines: tech/integration-guidelines.md
    - Operations:
      - Security: tech/security-requirements.md
      - Performance: tech/performance-requirements.md
      - CI/CD: tech/ci-cd.md
  - We & AI:
    - About Us: we-and-ai/about.md
    - AI Capabilities:
      - Project Areas: we-and-ai/project-areas-context.md
      - User Context: we-and-ai/user-context.md
      - Initiative Context: we-and-ai/initiative-context.md
    - Research: we-and-ai/creating-contexts.md

plugins:
  - search
  - include-markdown
  - mermaid2:
      version: 10.6.1
      arguments:
        securityLevel: 'loose'
        theme: default
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink
  - footnotes
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3
      slugify: !!python/name:pymdownx.slugs.uslugify

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Dolpheyn
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  homepage: https://antar.my
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
