name: Monorepo CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'docs/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'docs/**'
      - '.github/workflows/**'

# Allows cancelling in-progress runs of the same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-ci:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Verify Bun Installation
      run: |
        which bun
        bun --version
    
    - name: Install Frontend Dependencies
      run: bun install
      working-directory: ./frontend
    
    - name: Lint Frontend
      run: bun run lint
      working-directory: ./frontend
    
    - name: Run Frontend Unit Tests
      run: bun run test:unit
      working-directory: ./frontend
    
    - name: Run Frontend Component Tests
      run: bun run test:component
      working-directory: ./frontend
    
    - name: Setup Playwright
      run: bunx playwright install
      working-directory: ./frontend
    
    - name: Run Frontend E2E Tests
      run: bun run test:e2e
      working-directory: ./frontend
    
    - name: Build Frontend
      run: bun run build
      working-directory: ./frontend

  docs-build:
    name: Documentation Build
    runs-on: ubuntu-latest
    container: 
      image: python:3.11-slim
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Poetry
      run: |
        pip install poetry
        poetry --version
    
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
    
    - name: Load cached venv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-py3.11-${{ hashFiles('**/poetry.lock') }}
    
    - name: Install dependencies
      run: poetry install --with docs --no-interaction --no-root
    
    - name: Build Documentation
      run: poetry run mkdocs build
    
    # - name: Check Documentation Links
    #   run: |
    #     poetry run mkdocs serve &
    #     sleep 5 && pip install linkchecker && linkchecker http://127.0.0.1:8000
    
    - name: Deploy Documentation
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/site
