name: Monorepo CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'docs/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'docs/**'
      - '.github/workflows/**'

# Allows cancelling in-progress runs of the same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-ci:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Verify Bun Installation
      run: |
        which bun
        bun --version
    
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: bun install
    
    - name: Lint Frontend
      working-directory: ./frontend
      run: bun run lint
    
    - name: Run Frontend Unit Tests
      working-directory: ./frontend
      run: bun run test:unit
    
    - name: Run Frontend Component Tests
      working-directory: ./frontend
      run: bun run test:component
    
    - name: Setup Playwright
      working-directory: ./frontend
      run: bunx playwright install
    
    - name: Run Frontend E2E Tests
      working-directory: ./frontend
      run: bun run test:e2e
    
    - name: Build Frontend
      working-directory: ./frontend
      run: bun run build

  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'
        cache-path: ./frontend
    
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: NPM Audit
      working-directory: ./frontend
      run: |
        npm audit --audit-level=high || true
    
    - name: Snyk Vulnerability Scan
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
        args: --all-projects --severity-threshold=high

  docs-build:
    name: Documentation Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: |
          **/requirements.txt
          **/requirements-docs.txt
    
    - name: Install Documentation Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    
    - name: Build Documentation
      run: |
        cd docs
        mkdocs build
    
    - name: Deploy Documentation
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/site
