# Documentation Deployment Workflow
#
# This workflow automatically builds and deploys our documentation to GitHub Pages.
# It runs on:
# - Every push to main (builds and deploys)
# - Every pull request (builds only)
#
# Features:
# - Automatic deployment to GitHub Pages
# - Preview builds for pull requests
# - Mermaid diagram support
# - Dependency caching for faster builds
#
# Setup Required:
# 1. Go to repository Settings > Pages
# 2. Under "Build and deployment":
#    - Source: Select "GitHub Actions"
#
# The documentation will be available at:
# https://[username].github.io/antar/

name: Deploy Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements.txt
            **/requirements-docs.txt

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
      - name: Build documentation
        run: mkdocs build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./site

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://dolpheyn.github.io/antar/
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
